# A lot of inspiration from https://github.com/project-rig/rig_c_sa

language: python

sudo: false

cache:
    directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv_cache"

dist: xenial
os:
    - linux
    - osx
python:
    - 3.6
    - 3.7
    - 3.8

env:
    global:
    - USE_CYTHON=1

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - git submodule update --init

script:
    - python setup.py install
    - python setup.py test

after_success:
    - >
        if [ -n "$TRAVIS_TAG" ]; then
            # can only upload binaries for osx
            if [ "x$TRAVIS_OS_NAME" == "xosx" ]; then
                python setup.py bdist_wheel;
                # only submit sdist once
                if [ $TRAVIS_PYTHON_VERSION == 3.8 ]; then
                    python setup.py sdist
                fi
            fi
            # twine env variables are set in Travis web config
            twine upload --skip-existing dist/*;
        else
            echo "Will only deploy tagged releases"
        fi
