name: Run tests
run-name: ${{ github.actor }} testing freesasa-python
on: push
jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
        run: git submodule update --init
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py install
      - name: Run tests
        env:
          USE_CYTHON: 1
        run: python setup.py test
